name: Cypress Tests

on: push
#on:
#schedule:
# runs tests every day at 4am
#    - cron: '0 4 * * *'



jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install root dependencies
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info    #build: npm run build
          start: npm start
          browser: edge
          headed: true
          summary-title: 'Headed'
          spec: cypress/integration/examples/*.js
          record: true
          parallel: true
          tag: node-${{ matrix.node }}
          config: pageLoadTimeout=100000,requestTimeout=30000,defaultCommandTimeout=30000
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: a979428a-d58d-44e7-8a7b-954738a203b7
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: 9c692s
          # Get the short ref name of the branch that triggered the workflow run
          COMMIT_INFO_BRANCH: ${{ github.main }}
          
      # after the test run completes store videos and any screenshots
      - uses: actions/upload-artifact@v4
      # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

        
