name: Cypress Tests

on: push
#on:
#schedule:
# runs tests every day at 4am
#    - cron: '0 4 * * *'
# Install NPM dependencies, cache them correctly
# and run all Cypress tests
# - name: Install root dependencies
# run: npm ci

jobs:
  install:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'app'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      #      - name: Cypress install
      #        uses: cypress-io/github-action@v6

      - name: Compress
        working-directory: ./app
        run: Compress-Archive -Path ./* -Destination ./project.zip

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: project
          if-no-files-found: error
          path: app/project.zip

  cypress-run:
    runs-on: windows-latest
    needs: install
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: project
      #          path: app

      - name: Uncompress
        #        working-directory: ./app
        run: Expand-Archive ./project.zip -DestinationPath ./

      - name: Cypress install
        run: npx cypress install

      - name: Cypress test
        run: npm test
        continue-on-error: true

      - name: Upload screenshots & videos
        uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

